### ISSUE TITLE
Implement filter parameters in the position request

### ISSUE THREAD

**Issue by kamushkin** [ezlab/cega_gui#10]

**Comment by adousse** [comment]
Should be working with such argument:
filter=fieldname|startfilter|stopfilter
OR 
filter=status|noncoding
Fieldname can be any column name or length, startfilter and stopfilter are numbers from the sliders
For status, it can be 'all', 'coding', 'intronic', 'intergenic', 'noncoding'

**Comment by kamushkin** [comment]
Does it mean only one filter can be active at any time?

Maybe its better just make a separate optional parameter for each filter, like

..&score=min-max&length=min-max&status=text

Do we also need a separate input field (and parameter) for the position?

**Comment by adousse** [comment]
I will modify to have multiple filters. 
I did not realize the problem with position being in the "search" panel and in the "filter" one. Actually "Position" should be removed from the "filter" panel and stay only in the search one. I now realize the problem with the two buttons. It should be modified to have only one Submit button. New Issue about that.

**Comment by kamushkin** [comment]
I agree re single submit button - but then the question is how to set min/max slider values for the initial state (before the first request)? Maybe not to use sliders at all, just a text field where the user just types min-max, for example, 50-100 ?

**Comment by adousse** [comment]
Before the first request, is it possible not to show the filter panel? Just the search? and with the first results displayed the filter panel is available?

**Comment by kamushkin** [comment]
So when the user changes any parameter in the top search panel (implying the min-max ranges may change in the new results) we will hide filter panel and then show it again when the full search is done?

**Comment by adousse** [comment]
I didn't think about the new query. Actually in the end it's probably better to have it as you suggested, with a text field for score and length, usually the user has some predefined criterion that he could use easily this way. 
So text field for score and for length, dropdown for status.

**Comment by adousse** [comment]
Maybe having the filters displayed as [ textfield  ] - [  textfield ] might be better. If nothing is entered for one or the other, it will take the min or max. 
Just to know how to implement error handling there.
