### ISSUE TITLE
The position should return status='ok' when 'request=' parameter does not match known symbol

### ISSUE THREAD

**Issue by kamushkin** [ezlab/cega_gui#13]
Example - http://everest.unige.ch:8000/position?clade=vertebrata_human_69_all&species=Homo+Sapiens&request=xxx

The status='error' should be used for exceptions, where the application cannot continue and has to be terminated.

The invalid user input should be handled with status='ok' and the message explaining what was wrong and maybe the example of the correct input.

**Comment by adousse** [comment]
Changed status for non-match requests
