### ISSUE TITLE
Position request throws error when nothing is found

### ISSUE THREAD

**Issue by kamushkin** [ezlab/cega_gui#14]
Examples -

http://everest.unige.ch:8000/position?clade=vertebrata_human_69_all&species=Homo+Sapiens&request=7:0-100000

http://everest.unige.ch:8000/position?clade=vertebrata_human_69_all&species=Homo+Sapiens&request=7:20000000-27133612&length=1-20

**Comment by adousse** [comment]
Added status and message to handle no result error.
