### ISSUE TITLE
Add "Download" to get all selected elements from table. 

### ISSUE THREAD

**Issue by adousse** [ezlab/cega_gui#19]
Download button when clicked on shows small menu: 
2 radio buttons: download selected + number of selected rows/ download all
dropdown menu: fasta / bed
Go button

Download button should be on top of the table, next to "Search Results" rather than below, not troubling the table display with lots of elements

**Comment by adousse** [comment]
So in order to implement the Download abilities, I added an "id" column. selecting rows from the table should result in a URL like
"Download as Bed"
/bed?clade=euarchontoglires_human_85&species=Homo%20Sapiens&request=1,2,3,4,5,6,7,8,9,10,11,12
or
"Download as Fasta"
/fasta?clade=euarchontoglires_human_85&request=1,2,3,4,5,2539581,2539582,2539583,2539584,2539585

list of nuber in "request=, , ," are the id correspondig to each row.

**Comment by adousse** [comment]
While id is good for indexing, I went back to using block.element identifiers since it will get the set of elements for the fasta alignments. 
The URLS should therefore be of the form
"Download as Bed"
bed?clade=vertebrata_human_69_all&species=Homo Sapiens&request=494.1382,494.11,1.53
or
"Download as Fasta"
/fasta?clade=vertebrata_human_69_all&request=494.1382,494.11,1.53

list of nuber in "request=, , ," are the id correspondig to each row.

**Comment by kamushkin** [comment]
We need a different way to send 'Download All' request as the full list of IDs is not always available on the client side (due to pagination). Probably we should just send all search and filter parameters.

**Comment by adousse** [comment]
Right. I'm not in the office tomorrow but will check  for that on Monday

**Comment by adousse** [comment]
I would need a third possibility in the Download dropdown menu: Fasta Alignment that will go to 
/fastalign?clade=vertebrata_human_69_all&species=Homo Sapiens&request=494.1382,494.11,1.53

It is now possible to have "request=all,position" It is necessary to add the species to the request. Filters are handled too.
Examples:
/fasta?clade=vertebrata_human_69_all&species=Oreochromis Niloticus&request=all,GL831202.1:517808-538077&length=100-1000000

/bed?clade=vertebrata_human_69_all&species=Oreochromis Niloticus&request=all,GL831202.1:517808-538077&status=noncoding

**Comment by adousse** [comment]
Sorry for the changes again.
To allow for full list and removal of unselected rows:
To download all:
 "request=all_position"
To download all but the unchecked boxes:
 "request=all_position_no_xx.xx,xx.xx"

Examples:
 /fasta?clade=vertebrata_human_69_all&species=Oreochromis Niloticus&request=all_GL831202.1:517808-538077&length=100-1000000
/bed?&clade=vertebrata_human_69_all&species=Oreochromis+Niloticus&request=all_GL831202.1:517808-538077_no_1577.10,1577.12&length=100-1000000

**Comment by kamushkin** [comment]
I think we should not concatenate the different values into the single parameter `request` - we can just use separate parameters. Lets use `items` for the list of IDs and `all` to indicate inverted selection. When `all=true` the `items` list contains the IDs to be excluded (could be empty/missing, which means all). Also when `all=true` we include `request` and possibly `length`, `score` and `status` parameters from the main request.

Examples
Normal selection:
/fasta?clade=...&species=...&items=1577.10,1577.12

Select all:
/fasta?clade=...&species=...&request=...&all=true

all except 1577.10,1577.12
/fasta?clade=...&species=...&request=...&all=true&items=1577.10,1577.12

**Comment by adousse** [comment]
OK way cleaner, I implemented it the way you recommended. 
length, score and status are also available as filters.

**Comment by kamushkin** [comment]
Changed links to new format

**Comment by adousse** [comment]
I just corrected the errors in the code from previous implementations. Should be fine to get bed format too.
