### ISSUE TITLE
Add "UCSC" button with Link to UCSC for requested position

### ISSUE THREAD

**Issue by adousse** [ezlab/cega_gui#20]
I added "link_UCSC" to the result envelope. A button on top of the table next to search results with UCSC written on it redirects in new tab to this link.

**Comment by adousse** [comment]
In order not to mix things up there is a 'link_UCSC_region', for the whole table, and a 'link_UCSC' per row element

**Comment by kamushkin** [comment]
Done

**Comment by adousse** [comment]
Button should be "UCSC" not "USCS"

**Comment by kamushkin** [comment]
corrected
