### ISSUE TITLE
Change "chrom" "start "stop" to single "Position" column

### ISSUE THREAD

**Issue by adousse** [ezlab/cega_gui#24]
To make it more readable and easier for the user to select/paste, It would be better to merge the 3 first columns to one named "position" with the content of the form chrom:start-stop
Like
chr21:33031597-33041570
or
GL831202.1:517808-538077

**Comment by kamushkin** [comment]
Should we then drop sorting on start/stop?

**Comment by adousse** [comment]
sorting for this column will be sorting on start.
