### ISSUE TITLE
Implement pagination (skip, limit params) in the positions request

### ISSUE THREAD

**Issue by kamushkin** [ezlab/cega_gui#3]
As the total number of results can be large (>10000) we should initially only load a small number of rows and then load more when the user scrolls down (incremental loading).

The position request should accept the following parameters:
- `skip` - items to skip (default 0)
- `limit` - max items to send (default 100)

The results should return the total number of available rows in the `count` attribute

**Comment by adousse** [comment]
I added skip and limit so that results['data'] outputs the queried elements.
Now I am not sure how the sorting should be performed. Should I add an argument to the requesthandler for sorting by each field? Can it be handled differently on the application side?

**Comment by kamushkin** [comment]
opened separate issue #9 for sorting
