### ISSUE TITLE
Add "View all elements from this synteny block" in the row view

### ISSUE THREAD

**Issue by adousse** [ezlab/cega_gui#30]
In the row view, on top of the alignment, next to the element name, add a link "View all elements from this synteny block" that will go to 
/block?clade=...&species=...&block=.

**Comment by kamushkin** [comment]
How we should display the results? Where?

**Comment by adousse** [comment]
Normally it redirects to the standard table with all elements from the block. The ideal would be to just display the table with the element the row that was clicked on still expanded, if that's feasible.
