### ISSUE TITLE
Add functionality: Chromosome browsing on home page.

### ISSUE THREAD

**Issue by adousse** [ezlab/cega_gui#33]
I would like to add a new functionality, on the home page. 
A package allows to display and get position from chromosome drawings. 
http://pparsons.github.io/angular-chromosome-vis/
https://github.com/pparsons/angular-chromosome-vis

I would like to integrate this, displaying all chromosomes (1-22,x,y). The user could select (only one selector) the part of a chromosome he likes and "Submit" to view the results in CEGA table. The "Submit" will redirect to 
position?clade=vertebrata_human_69_all&species=Homo+Sapiens&request=POSITION_FROM_CHROMOSOME_DISPLAY&status=noncoding

Related to that, will using this package require me to install it on our server? It is feasible, but since the server is not up to date, it might be problematic so I would like to know in advance.

**Comment by kamushkin** [comment]
Put chromosome widgets into iframe to isolate Angular from the rest of the application

**Comment by kamushkin** [comment]
Should we copy the data locally to improve initialization speed (and allow caching)?

**Comment by adousse** [comment]
I downloaded the data for each chromosome separately and now they are in 
/static/data/karyotype/chr1
/static/data/karyotype/chr2
...
Tell me if they are not accessible.

**Comment by kamushkin** [comment]
The data response should contain header Content-Type: text/xml - otherwise JSDAS parser breaks (the server sends them as text/html now).

**Comment by adousse** [comment]
I tried to modify that. Links should now be like
/karyotype?chrom=chr1
/karyotype?chrom=chr2
...

**Comment by kamushkin** [comment]
ok, works now

**Comment by kamushkin** [comment]
To allow caching you should also add cache-control header -
Cache-Control:public, max-age=3600

**Comment by adousse** [comment]
I added Cache-control to the header.

**Comment by kamushkin** [comment]
changed selection to update `request` field instead of immediate navigation

**Comment by adousse** [comment]
Looks good and working fine, thanks!
