### ISSUE TITLE
Do not send image_file URL for missing images

### ISSUE THREAD

**Issue by kamushkin** [ezlab/cega_gui#36]
Request to `elements` service returns automatically generated image_file URL even if the image file is not present in the cega_data directory - 

http://cega.ezlab.org/?clade=vertebrata_human_69_all&species=Homo+Sapiens+(Human)&request=chr1%3A20100001-23600000&status=noncoding

![image](https://cloud.githubusercontent.com/assets/9464404/9766388/e359f346-5718-11e5-9537-be5729d32a45.png)

http://ceggdev.ezlab.org/cega_data/31.4_vertebrata_human_69_all.jpg

![image](https://cloud.githubusercontent.com/assets/9464404/9766467/564acaf6-5719-11e5-82f0-1170f72aebbd.png)

**Comment by adousse** [comment]
If the screenshot image file does not exists it will now return URL to UCSC logo image.

**Comment by adousse** [comment]
The UCSC logo seemed confusing. 
Instead if the image is missing the URL sent as response will be empty , '' .
When it is the case, the "link_UCSC" should be shown as a hyperlinked sentence:

No screenshot currently available for this element. [See it on UCSC.](http://genome.ucsc.edu/cgi-bin/hgTracks?org=human&db=hg19&position=chr3:55108596-55110799&wgEncodeReg=full&wgEncodeRegTfbsClusteredV3=dense&wgRna=hide&cpgIslandExt=hide&ensGene=hide&mrna=hide&intronEst=hide&mgcGenes=hide&cons44way=hide&snp130=hide&snpArray=hide&refGene=pack&wgEncodeRegMarkPromoter=hide&knownGene=hide&rmsk=hide&phyloP46wayPlacental=hide&track1=full&phyloP100wayAll=hide&multiz100way=hide&wgEncodeBroadHmmH1hescHMM=dense&snp142Common=hide&hgt.customText=http://ceggdev.ezlab.org/cega_data/SORTED_ALL_CNCS_VERTEBRATA.bed)
