### ISSUE TITLE
When request is a gene name, add genomic position in "Search result" header or "No results"

### ISSUE THREAD

**Issue by adousse** [ezlab/cega_gui#37]
When a gene name is entered as request (Example HOXA1 http://cega.ezlab.org/?clade=amniota_human_55&species=Homo+Sapiens+%28Human%29&request=HOXA1&status=noncoding ), the request is processed and redirected to CEGA with the position as /position?clade=amniota_human_55&species=Homo%20Sapiens&request=chr7:27132112-27136115&status=noncoding . 

Could the genomic position here chr7:27132112-27136115 be added on top of the table, like

Search results: HOXA1 chr7:27132112-27136115 : 7 elements

And when no result is found:

No results found for IL2RA chr10:6052152-6104788 ...

**Comment by kamushkin** [comment]
Can we have a `request` field in the response which, if present, will be shown instead of `request` user input?

**Comment by adousse** [comment]
When the position of the gene is found, the new request field is the position. Is it possible to get it?

**Comment by kamushkin** [comment]
No. Firefox and Chrome support `responseURL`, IE and Safari don't -
http://stackoverflow.com/questions/8056277/how-to-get-response-url-in-xmlhttprequest

**Comment by adousse** [comment]
OK so I hope I understood correctly. I added a "request" field to the results returned.

**Comment by kamushkin** [comment]
Yes, but the field should then contain 'HOXA1 chr7:27132112-27136115', or anything you want to show instead of the original request text in the status area.

**Comment by adousse** [comment]
OK, it should work this way now.

**Comment by kamushkin** [comment]
Looks good. I assume the `request` field is always present in /positions, so I will show its content in the status (ignoring the original `request` parameter, which is still visible in the input box).
