### ISSUE TITLE
Add hyperlink to otherDB column

### ISSUE THREAD

**Issue by adousse** [ezlab/cega_gui#39]
Add hyperlinks to other databases to the letter code in the OtherDB column. When clicked on the letter, itopens the hyperlink to new tab.

C => http://condor.nimr.mrc.ac.uk/
V => http://enhancer.lbl.gov/
U => http://ccg.vital-it.ch/UCNEbase/

**Comment by adousse** [comment]
Actually each element with reference to one other DB should link to this element in the other database. I'll check on OrthoDB how this is done. 
No need to implement this yet.

**Comment by adousse** [comment]
I changed the values for the "Other DB" columns from 0/1 to the IDs of the element in the specific databases. 
The hyperlink has to be built the following way:

V : http://enhancer.lbl.gov/cgi-bin/imagedb3.pl?form=presentation&show=1&organism_id=1&experiment_id={vista}
C : http://condor.nimr.mrc.ac.uk/cgi-bin/show_cne.cgi?cneid={condor}
U: http://ccg.vital-it.ch/UCNEbase/view.php?data=ucne&entry={ucne}

So clicking on a letter in the table will open a new tab to the specific hyperlink.

Also if the column (vista / ucne / condor) value is '0' letter is not displayed.

**Comment by kamushkin** [comment]
Could you send empty string instead of "0" for condor/ucne? 0 (number) is considered 'empty' by the template engine, while "0" (string) is not.

**Comment by adousse** [comment]
Sure, it is done now.
