### ISSUE TITLE
Add Export button to Multiple sequence alignment panel in rows

### ISSUE THREAD

**Issue by adousse** [ezlab/cega_gui#42]
In the BioJS MSA tool, it would be nice to have the Export button on top of each alignment directly. It should be available from the BioJS tool itself.

**Comment by kamushkin** [comment]
Looks like MSA menu is not configurable, i.e. I cannot display just Export button, only the whole menu. However I can call MSA API export function and add my own link, like this -

![image](https://cloud.githubusercontent.com/assets/9464404/10019174/1bafba82-613c-11e5-8567-0ab384f41f74.png)

**Comment by adousse** [comment]
Does it allow to export image as well as sequence then? If it is the case it is good enough then.

**Comment by kamushkin** [comment]
I can add second link for the image export

**Comment by adousse** [comment]
OK then let's have a "Download alignment" and a "Export image" link.

**Comment by adousse** [comment]
For the moment the "export image" exports only the visible part of the alignment without the names and other information. Is it possible to make it export the whole alignment as image, with the names and the whole sequence?

**Comment by kamushkin** [comment]
No, that is not possible. The built-in menu triggers the same API call and produces the same result -

MSA source code -
https://github.com/greenify/msa/blob/master/src/menu/views/ExportMenu.coffee#L45

MSA docs -
https://github.com/greenify/msa#export-and-save

Our code -
https://github.com/ezlab/cega_gui/blob/master/static/js/elements.js#L119

We are calling the same function `saveAsImg(widget, filename)` which does not have any other parameters -

https://github.com/greenify/msa/blob/master/src/utils/export.coffee#L88

The function just dumps current canvas image into the file.

**Comment by kamushkin** [comment]
Well, it is possible to create an image in a similar way for the whole sequence, but then we have to draw it ourselves. Not sure how much MSA code we can reuse here - could be a significant work.

**Comment by adousse** [comment]
OK, thanks for looking into it.
We will then keep it the way it is.
