### ISSUE TITLE
Should we merge the left-side table into MSA widget in the expanded row?

### ISSUE THREAD

**Issue by kamushkin** [ezlab/cega_gui#5]
It is possible to modify MSA widget to include more text columns in the left labels area instead of having a separate table on the left. This saves a bit of space and also keeps rows in sync when scrolling the widget vertically.

![image](https://cloud.githubusercontent.com/assets/9464404/8226627/95f3d4e6-15a0-11e5-851a-9c8ef65a115e.png)

Should we go like this or keep a separate table as in original spec?

**Comment by adousse** [comment]
Yes good sugestion, it looks cleaner to have it all in the widget. Is it possible to add column names to clarify what's their content? 
I've also seen that the widget allows for data retrieval as well, maybe it would be a good idea to use it if possible, for the user to retrieve the data for one single element.

**Comment by kamushkin** [comment]
Yes, I will add the column names - that should be possible. We can also enable some functionality of the widget via its own menu.

**Comment by kamushkin** [comment]
Done.
